import { getDb } from "../api/queries/connection";
import { properties } from "./schema";

async function seed() {
  const db = getDb();
  console.log("Seeding database...");

  // Seed 12 sample properties — 6 Kampala, 6 Hoima (AFCON 2027)
  await db.insert(properties).values([
    {
      title: "Kampala Central Hub",
      description:
        "Modern serviced apartments in the heart of Kampala. Walking distance to shops, restaurants, and nightlife. Perfect for fans who want to be close to the action.",
      location: "Kampala",
      address: "Plot 42, Kampala Road, Central Business District",
      pricePerNight: 85000,
      capacity: 4,
      bedrooms: 2,
      bathrooms: 2,
      amenities: JSON.stringify([
        "WiFi",
        "Air Conditioning",
        "Kitchen",
        "TV",
        "Washer",
        "Free Parking",
        "Security",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
        "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
      ]),
      isKitufu: 0,
      hasShuttle: 1,
      isGroupFriendly: 1,
      distanceToStadium: "20 min",
      status: "approved",
      ownerId: 1,
    },
    {
      title: "Mandela Walk Suites",
      description:
        "Elegant suites on Mandela National Stadium Walk. Wake up to views of the stadium and enjoy premium match-day access with dedicated shuttle service.",
      location: "Kampala",
      address: "Mandela National Stadium Road, Namboole",
      pricePerNight: 120000,
      capacity: 2,
      bedrooms: 1,
      bathrooms: 1,
      amenities: JSON.stringify([
        "Stadium View",
        "WiFi",
        "Air Conditioning",
        "Room Service",
        "Mini Bar",
        "Shuttle Service",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/photo-1618773928121-c32242e63f39",
        "https://images.unsplash.com/photo-1590490360182-c33d57733427",
      ]),
      isKitufu: 1,
      hasShuttle: 1,
      isGroupFriendly: 0,
      distanceToStadium: "5 min",
      status: "approved",
      ownerId: 1,
    },
    {
      title: "Nakasero Heights",
      description:
        "Luxury hilltop apartments in Nakasero with panoramic city views. Premium amenities for discerning guests seeking comfort and style during AFCON 2027.",
      location: "Kampala",
      address: "Nakasero Hill Drive, Nakasero",
      pricePerNight: 150000,
      capacity: 6,
      bedrooms: 3,
      bathrooms: 3,
      amenities: JSON.stringify([
        "City View",
        "WiFi",
        "Pool",
        "Gym",
        "Kitchen",
        "Balcony",
        "Housekeeping",
        "Security",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
        "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
      ]),
      isKitufu: 0,
      hasShuttle: 1,
      isGroupFriendly: 1,
      distanceToStadium: "25 min",
      status: "approved",
      ownerId: 1,
    },
    {
      title: "Kololo View Apartments",
      description:
        "Bright, airy apartments in the upscale Kololo neighborhood. Close to embassies, restaurants, and entertainment. Ideal for international visitors.",
      location: "Kampala",
      address: "Plot 15, Kololo Road, Kololo",
      pricePerNight: 95000,
      capacity: 4,
      bedrooms: 2,
      bathrooms: 2,
      amenities: JSON.stringify([
        "WiFi",
        "Air Conditioning",
        "Kitchen",
        "Garden",
        "Parking",
        "Security",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
        "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
      ]),
      isKitufu: 0,
      hasShuttle: 0,
      isGroupFriendly: 1,
      distanceToStadium: "30 min",
      status: "approved",
      ownerId: 1,
    },
    {
      title: "Namboole Fan Lodge",
      description:
        "Budget-friendly lodge just minutes from Mandela National Stadium. Clean, comfortable rooms with all essentials. The best value for match-going fans.",
      location: "Kampala",
      address: "Namboole Road, Kireka",
      pricePerNight: 35000,
      capacity: 2,
      bedrooms: 1,
      bathrooms: 1,
      amenities: JSON.stringify([
        "WiFi",
        "Fan",
        "TV",
        "Shared Kitchen",
        "Parking",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/photo-1631049307264-da0ec9d70304",
        "https://images.unsplash.com/photo-1566073771259-6a8506099945",
      ]),
      isKitufu: 1,
      hasShuttle: 1,
      isGroupFriendly: 0,
      distanceToStadium: "8 min",
      status: "approved",
      ownerId: 1,
    },
    {
      title: "Bugolobi Riverside",
      description:
        "Serene riverside apartments in Bugolobi. Enjoy tranquil gardens and Lake Victoria breezes while staying connected to the city center.",
      location: "Kampala",
      address: "Spring Close, Bugolobi",
      pricePerNight: 75000,
      capacity: 4,
      bedrooms: 2,
      bathrooms: 2,
      amenities: JSON.stringify([
        "WiFi",
        "Air Conditioning",
        "Kitchen",
        "Garden",
        "Pool",
        "Lake View",
        "Parking",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
        "https://images.unsplash.com/photo-1571896349842-33c89424de2d",
      ]),
      isKitufu: 0,
      hasShuttle: 0,
      isGroupFriendly: 1,
      distanceToStadium: "35 min",
      status: "approved",
      ownerId: 1,
    },
    {
      title: "Hoima Stadium Residence",
      description:
        "The closest accommodation to Kigaaya Stadium in Hoima. Purpose-built for AFCON 2027 with match-day packages and stadium shuttle included.",
      location: "Hoima",
      address: "Kigaaya Stadium Road, Hoima",
      pricePerNight: 110000,
      capacity: 4,
      bedrooms: 2,
      bathrooms: 2,
      amenities: JSON.stringify([
        "Stadium View",
        "WiFi",
        "Air Conditioning",
        "Kitchen",
        "Shuttle Service",
        "Room Service",
        "Parking",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/photo-1564501049412-61c2a3083791",
        "https://images.unsplash.com/photo-1584132967334-10e028bd69f7",
      ]),
      isKitufu: 1,
      hasShuttle: 1,
      isGroupFriendly: 1,
      distanceToStadium: "3 min",
      status: "approved",
      ownerId: 1,
    },
    {
      title: "Bunyoro Cultural Inn",
      description:
        "Experience authentic Bunyoro culture with modern comforts. Traditional-inspired architecture with contemporary amenities in the heart of Hoima.",
      location: "Hoima",
      address: "Main Street, Hoima Town",
      pricePerNight: 55000,
      capacity: 2,
      bedrooms: 1,
      bathrooms: 1,
      amenities: JSON.stringify([
        "WiFi",
        "Cultural Experience",
        "Restaurant",
        "Garden",
        "Parking",
        "Security",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4",
        "https://images.unsplash.com/photo-1445019980597-93fa8acb246c",
      ]),
      isKitufu: 0,
      hasShuttle: 0,
      isGroupFriendly: 0,
      distanceToStadium: "15 min",
      status: "approved",
      ownerId: 1,
    },
    {
      title: "Lake Albert View Lodge",
      description:
        "Stunning views of Lake Albert from every room. Relax in nature while being a short drive from the stadium. Perfect for groups seeking a scenic retreat.",
      location: "Hoima",
      address: "Lake Albert Road, Hoima",
      pricePerNight: 70000,
      capacity: 8,
      bedrooms: 4,
      bathrooms: 4,
      amenities: JSON.stringify([
        "Lake View",
        "WiFi",
        "Kitchen",
        "BBQ Area",
        "Garden",
        "Parking",
        "Group Space",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/photo-1563911302283-d2bc129e7c1f",
        "https://images.unsplash.com/photo-1587061949409-02df41d5e562",
      ]),
      isKitufu: 0,
      hasShuttle: 1,
      isGroupFriendly: 1,
      distanceToStadium: "20 min",
      status: "approved",
      ownerId: 1,
    },
    {
      title: "Kigaaya Fan Village",
      description:
        "Vibrant fan village near Kigaaya Stadium. Shared and private rooms available. Join fellow supporters for an unforgettable AFCON atmosphere.",
      location: "Hoima",
      address: "Kigaaya Quarter, near Stadium, Hoima",
      pricePerNight: 25000,
      capacity: 6,
      bedrooms: 2,
      bathrooms: 2,
      amenities: JSON.stringify([
        "WiFi",
        "Shared Lounge",
        "Kitchen",
        "Fan",
        "Parking",
        "Community Events",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/photo-1555854877-bab0e564b8d5",
        "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6",
      ]),
      isKitufu: 1,
      hasShuttle: 1,
      isGroupFriendly: 1,
      distanceToStadium: "5 min",
      status: "approved",
      ownerId: 1,
    },
    {
      title: "Mparo Royal Suites",
      description:
        "Premium suites near the historic Mparo Tombs. Combines cultural heritage with luxury living for an unparalleled AFCON experience in Hoima.",
      location: "Hoima",
      address: "Mparo Hill Road, Hoima",
      pricePerNight: 130000,
      capacity: 4,
      bedrooms: 2,
      bathrooms: 2,
      amenities: JSON.stringify([
        "WiFi",
        "Air Conditioning",
        "Kitchen",
        "Premium Bedding",
        "Garden",
        "Cultural Tours",
        "Parking",
        "Security",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/photo-1591088398332-8a7791972843",
        "https://images.unsplash.com/photo-1578683010236-d716f9a3f461",
      ]),
      isKitufu: 0,
      hasShuttle: 1,
      isGroupFriendly: 1,
      distanceToStadium: "12 min",
      status: "approved",
      ownerId: 1,
    },
    {
      title: "Hoima Hills Retreat",
      description:
        "Peaceful hillside retreat overlooking Hoima town. Spacious rooms, fresh air, and beautiful sunsets. A perfect escape after exciting match days.",
      location: "Hoima",
      address: "Hoima Hills, overlooking town center",
      pricePerNight: 60000,
      capacity: 4,
      bedrooms: 2,
      bathrooms: 2,
      amenities: JSON.stringify([
        "Scenic View",
        "WiFi",
        "Kitchen",
        "Balcony",
        "Garden",
        "Parking",
        "Hiking Trails",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/photo-1518780664697-55e3ad937233",
        "https://images.unsplash.com/photo-1587595431973-160d0d94add1",
      ]),
      isKitufu: 0,
      hasShuttle: 0,
      isGroupFriendly: 1,
      distanceToStadium: "18 min",
      status: "approved",
      ownerId: 1,
    },
  ]);

  console.log("Seeded 12 AFCON 2027 properties (6 Kampala, 6 Hoima).");
  console.log("Done.");
  process.exit(0); // close MySQL connection pool
}

seed();
